[build]
  functions = "netlify/functions"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/cloudinary-images"
  status = 200
  conditions = { Language = ["en"] }
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
